# Generated by Django 4.2.6 on 2023-10-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_requestlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='path',
            field=models.TextField(blank=True),
        ),
    ]
