# Generated by Django 4.2.6 on 2023-10-15 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_requestlog_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestlog',
            old_name='data',
            new_name='source',
        ),
    ]
